Repository game-by-virtuals/game-node, pull requests merged in 2025-01, with the labels that each got.

#13 Add Allora plugin
  plugins/alloraPlugin/.gitignore
  plugins/alloraPlugin/.npmignore
  plugins/alloraPlugin/README.md
  plugins/alloraPlugin/package-lock.json
  plugins/alloraPlugin/package.json
  plugins/alloraPlugin/src/alloraPlugin.ts
  plugins/alloraPlugin/src/example.ts
  plugins/alloraPlugin/src/index.ts
  plugins/alloraPlugin/tsconfig.json
Labels: plugin

#11 fix typos
  README.md
Labels: documentation

#12 added telegram & discord client
  plugins/discordPlugin/.gitignore
  plugins/discordPlugin/.npmignore
  plugins/discordPlugin/README.md
  plugins/discordPlugin/__test__/DiscordPlugin.test.ts
  plugins/discordPlugin/jest.config.js
  plugins/discordPlugin/package.json
  plugins/discordPlugin/src/discordPlugin.ts
  plugins/discordPlugin/src/example.ts
  plugins/discordPlugin/src/index.ts
  plugins/discordPlugin/tsconfig.json
  plugins/telegramPlugin/.gitignore
  plugins/telegramPlugin/.npmignore
  plugins/telegramPlugin/README.md
  plugins/telegramPlugin/__test__/TelegramPlugin.test.ts
  plugins/telegramPlugin/jest.config.js
  plugins/telegramPlugin/package-lock.json
  plugins/telegramPlugin/package.json
  plugins/telegramPlugin/src/example.ts
  plugins/telegramPlugin/src/index.ts
  plugins/telegramPlugin/src/telegramPlugin.ts
  plugins/telegramPlugin/tsconfig.json
Labels: plugin

#18 Update README and description
  plugins/discordPlugin/README.md
  plugins/telegramPlugin/README.md
Labels: documentation

#5 Add save method and static load method to GameAgent class
  src/agent.ts
Labels: enhancement

#20 Add more description for telegram and discord
  plugins/discordPlugin/README.md
  plugins/discordPlugin/src/example.ts
  plugins/telegramPlugin/README.md
Labels: documentation

#7 feat: add an RSS3 plugin
  plugins/rss3Plugin/.gitignore
  plugins/rss3Plugin/.npmignore
  plugins/rss3Plugin/README.md
  plugins/rss3Plugin/package-lock.json
  plugins/rss3Plugin/package.json
  plugins/rss3Plugin/pnpm-lock.yaml
  plugins/rss3Plugin/src/example.ts
  plugins/rss3Plugin/src/index.ts
  plugins/rss3Plugin/src/rss3Plugin.ts
  plugins/rss3Plugin/tsconfig.json
Labels: plugin

#24 feat: added game-starter
  game-starter/.env.example
  game-starter/.gitignore
  game-starter/README.md
  game-starter/package-lock.json
  game-starter/package.json
  game-starter/src/agent.ts
  game-starter/src/functions.ts
  game-starter/src/index.ts
  game-starter/src/worker.ts
  game-starter/tsconfig.json
Labels: enhancement
